import { Service, Product } from './types';

export const INITIAL_SERVICES: Service[] = [
  // --- WAXING SERVICES ---
  {
    id: 'wax-1',
    name: 'Complete Rica Waxing (Full Arms, Legs & Underarms)',
    category: 'Waxing',
    price: 1099,
    durationMinutes: 70,
    benefits: ['Colophony-free, reduced redness', 'Excellent hair removal from root', 'Gentle on sensitive skin', 'Slightly brightens skin tone'],
    ingredients: ['Glyceryl Rosinate (Natural resin)', 'Beeswax', 'Titanium Dioxide', 'Vegetable Oil bases'],
    skinType: 'All skin types, including highly sensitive skin',
    procedure: ['Cleanse area with pre-wax lotion', 'Apply ultra-thin layer of warm Rica wax', 'Press strip and pull opposite to hair growth', 'Post-wax soothing oil massage'],
    aftercare: ['Avoid hot water shower for 24 hours', 'Do not scratch or touch excessively', 'Apply fresh aloe vera gel', 'Avoid direct sun exposure'],
    safety: ['Check wax temperature before application', 'Patch test on small area first', 'Do not double-dip spatulas'],
    hygiene: ['Single-use disposable wax strips and spatulas', 'Sanitized bed sheets', 'Technician wears gloves and sterile mask'],
    imageSeed: 'rica_complete'
  },
  {
    id: 'wax-2',
    name: 'Complete Honey Waxing (Full Arms, Legs & Underarms)',
    category: 'Waxing',
    price: 699,
    durationMinutes: 70,
    benefits: ['Natural moisturizing power of honey', 'Removes dead skin cells', 'Leaves skin feeling soft and clean'],
    ingredients: ['Natural Honey extract', 'Sugar syrup', 'Citric acid', 'Purified water'],
    skinType: 'Normal and dry skin',
    procedure: ['Pre-wax sanitization with wipes', 'Apply warm water-soluble honey wax', 'Gently press non-woven strip and pull', 'Cleanse skin residues with damp warm towel'],
    aftercare: ['Apply moisturizing lotion', 'Wear comfortable loose cotton shirts', 'Avoid intense gymming for 12 hours'],
    safety: ['Do not apply on broken skin or burns', 'Keep wax temperature warm and safe'],
    hygiene: ['Disposable sheets', 'Spatulas safely disposed', 'Alcohol wipes for hands before contact'],
    imageSeed: 'honey_complete'
  },
  {
    id: 'wax-3',
    name: 'Honey Aloe Vera Waxing (Full Arms, Legs & Underarms)',
    category: 'Waxing',
    price: 699,
    durationMinutes: 70,
    benefits: ['Aloe Vera offers instant cooling relief', 'Reduces post-wax burning sensation', 'Super hydration effect'],
    ingredients: ['Aloe Vera Barbadensis leaf juice', 'Natural Bee Honey', 'Sucrose', 'Glycerin'],
    skinType: 'Dry and sun-damaged skin',
    procedure: ['De-grease skin surface', 'Apply aloe-infused wax thin layer', 'Remove cleanly with quick-release strip', 'Apply calming aloe spray'],
    aftercare: ['No steam baths or saunas for 24 hours', 'Apply fragrance-free light moisturizer'],
    safety: ['Do not apply on irritated skin', 'Strictly test heat thresholds'],
    hygiene: ['Fresh bed wrapper', 'Individually wrapped disposable spatulas', 'Hands sanitized with surgical grade scrub'],
    imageSeed: 'honey_aloe_complete'
  },
  {
    id: 'wax-4',
    name: 'Rica Dark Chocolate & Brazilian Waxing (Full Arms, Legs & Underarms)',
    category: 'Waxing',
    price: 1099,
    durationMinutes: 70,
    benefits: ['Rich nourishing anti-oxidant properties', 'Excellent relaxing aroma of real cocoa', 'D-tan benefits while moisturizing'],
    ingredients: ['Real Cocoa Butter extract', 'Glyceryl Rosinate', 'Coconut oil', 'Sweet almond oil'],
    skinType: 'Dehydrated, dry and mature skins',
    procedure: ['Pre-depilatory gel cooling massage', 'Smooth warm chocolate wax application', 'Firm strip press and release', 'Coconut soothing lotion cleanup'],
    aftercare: ['Avoid chlorine pools for 24 hours', 'Nourish with high-quality moisturizer daily'],
    safety: ['Strict caution for cocoa/nut allergies', 'Always test heat with therapist finger first'],
    hygiene: ['Sanitized metal waxing heater container', 'Disposable spatulas only', 'Sterilized equipment and sheets'],
    imageSeed: 'rica_chocolate'
  },
  {
    id: 'wax-5',
    name: 'Rica Roll-On Waxing (Full Arms, Legs & Underarms)',
    category: 'Waxing',
    price: 1399,
    durationMinutes: 60,
    benefits: ['Fast, uniform application with zero patchiness', 'Hygiene-first rollers directly rolled on', 'Exquisite hair-free smooth finish'],
    ingredients: ['Vegetable oil base', 'Titanium dioxide', 'Zinc oxide', 'Cera Alba'],
    skinType: 'All skin types, including sensitive skin',
    procedure: ['Pre-treatment cooling mist', 'Direct sanitized cartridge rolling application', 'Strip pressing with specialized technique', 'Apply soothing post-wax oil mist'],
    aftercare: ['Wear breathable clothing', 'Avoid direct scrubbing or scratching'],
    safety: ['Inspect roller cartridge spin comfort', 'Adjust roller temperature dynamically'],
    hygiene: ['Individually dedicated sanitizer wax cartridges', 'Disposable strips and wraps'],
    imageSeed: 'rica_rollon'
  },
  {
    id: 'wax-6',
    name: 'Cirepil Roll-On Waxing (Full Arms, Legs & Underarms)',
    category: 'Waxing',
    price: 1699,
    durationMinutes: 60,
    benefits: ['Premium French formulation', 'Encapsulates hair from very root', 'Pain-less sensory wax properties'],
    ingredients: ['Cirepil patented Elastomer', 'Mineral oils free', 'Titanium dioxide'],
    skinType: 'Excellent for very thick, coarse hair on sensitive skin',
    procedure: ['Cleanse with Jasmine Pre-wax oil', 'Apply thin, precise roller wax layer', 'Quick painless wax pull with professional grip', 'Post-wax refreshing cooling gel massage'],
    aftercare: ['Avoid heavy sweat or workout for 24h', 'Hydrate skin cells with soothing gel'],
    safety: ['Monitor roller velocity', 'Adjust cartridge base heat settings strictly'],
    hygiene: ['Sealed personal hygiene cartridges', 'Double gloves sterilization protocol'],
    imageSeed: 'cirepil_rollon'
  },
  {
    id: 'wax-7',
    name: 'Full Arms & Underarms (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 399,
    durationMinutes: 30,
    benefits: ['Smooth arms with aloe-comfort armpit prep', 'Removes stubble completely'],
    ingredients: ['Aloe Barbadensis extract', 'Glucose', 'Citric juice'],
    skinType: 'Sensitive armpits and dry arms',
    procedure: ['Sanitize and dust armpits', 'Apply warm aloe honey wax layer', 'Flick strip firmly and cleanly'],
    aftercare: ['Avoid spray deodorants or perfumes for 24 hours', 'Keep armpits ventilated'],
    safety: ['Check underarm lymph nodes state first', 'Never double wax the same patch twice'],
    hygiene: ['Therapist sanitizes hands prior to underarms prep', 'Single-use strips only'],
    imageSeed: 'half_honey_aloe'
  },
  {
    id: 'wax-8',
    name: 'Full Arms & Underarms (Rica Chocolate or Brazilian)',
    category: 'Waxing',
    price: 699,
    durationMinutes: 30,
    benefits: ['Aromatic relaxation experience', 'Nourishes dry underarms and prevents skin darkening'],
    ingredients: ['Theobroma Cacao seed butter', 'Natural rosinate', 'Almond oil'],
    skinType: 'All skin types with hair pigementation',
    procedure: ['Cleanse with Rica cotton lotion', 'Warm wax application', 'Steady wax pulling and cleaning with tea tree oil'],
    aftercare: ['Avoid underarm rolls-ons for 2 days', 'Moisturize gently'],
    safety: ['Test heat strictly around inner upper arm', 'No waxing on bruised skin'],
    hygiene: ['Disinfected sanitizers before physical touch', 'Spatula disposal immediately'],
    imageSeed: 'half_rica_choc'
  },
  {
    id: 'wax-9',
    name: 'Full Arms & Underarms (Rica Roll-On)',
    category: 'Waxing',
    price: 799,
    durationMinutes: 30,
    benefits: ['Mess-free cartridge waxing', 'Pain-conscious roll-on action on underarms'],
    ingredients: ['Patented Rica liquid formula', 'Organic wax base'],
    skinType: 'Normal to dry skin',
    procedure: ['Cooling preparation with tea tree mist', 'Gentle roll-on slide', 'Rapid non-woven strip pull'],
    aftercare: ['Soften with soothing emulsion', 'Avoid synthetic wear'],
    safety: ['Check underarm sensitivity levels', 'Proper skin tension during pull'],
    hygiene: ['Sealed specialized personal rollers used only'],
    imageSeed: 'half_rica_rollon'
  },
  {
    id: 'wax-10',
    name: 'Full Arms & Underarms (Cirepil Roll-On)',
    category: 'Waxing',
    price: 899,
    durationMinutes: 30,
    benefits: ['Ultra luxurious French feel', 'No post-wax stickiness, deep smooth skin finish'],
    ingredients: ['Cirepil elastomer formulation', 'Jasmine extracts'],
    skinType: 'Highly sensitive armpit zones',
    procedure: ['Apply pre-wax rose oil layer', 'Slide warm roll-on cartridge', 'Firm strip action and lavender finish lotion'],
    aftercare: ['Dab with cold towel if redness occurs', 'Apply calamine cream'],
    safety: ['Maintain low heater thermostat', 'Gently tension underarm creases'],
    hygiene: ['Hospital-grade hygiene standards and sterilized cartridges'],
    imageSeed: 'half_cirepil'
  },
  {
    id: 'wax-11',
    name: 'Half Legs (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 252,
    durationMinutes: 20,
    benefits: ['Quick exfoliation', 'Silky half legs to knees'],
    ingredients: ['Agave syrup', 'Aloe gel juice ext', 'Distilled water'],
    skinType: 'Normal, Dry skins',
    procedure: ['Prep with water wipe', 'Apply warm honey wax', 'Smooth strip peel', 'Hydrating gel wash'],
    aftercare: ['Apply moisturizing defense layer', 'Avoid direct sun for 12 hours'],
    safety: ['Proper temperature checks'],
    hygiene: ['Standard disposable sheet layover'],
    imageSeed: 'half_legs_honey'
  },
  {
    id: 'wax-12',
    name: 'Half Legs (Rica Dark Chocolate)',
    category: 'Waxing',
    price: 379,
    durationMinutes: 20,
    benefits: ['Antioxidant nourishment', 'Exquisite skin-glow on calf area'],
    ingredients: ['Cocoa extracts', 'Beeswax base'],
    skinType: 'Dry and dull skin legs',
    procedure: ['Cleanse', 'Warm chocolate wax spatula glide', 'Firm strip separation', 'Soothing cocoa oil post-care'],
    aftercare: ['Avoid synthetic tights for 24h'],
    safety: ['Never apply wax over varicose veins'],
    hygiene: ['Individual disposable cups and spatulas'],
    imageSeed: 'half_legs_choc'
  },
  {
    id: 'wax-13',
    name: 'Half Arms Only (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 249,
    durationMinutes: 20,
    benefits: ['Quick tan removal', 'Smooth glowing arms from elbows down'],
    ingredients: ['Honey', 'Aloe juice', 'Fruit citric base'],
    skinType: 'All skins',
    procedure: ['Prep surface', 'Apply warm wax layer', 'Quick strip release', 'Refresh with aqua mist'],
    aftercare: ['Lotion application', 'Avoid sun exposure'],
    safety: ['Do not scratch red bumps'],
    hygiene: ['Single-use applicator stick used once'],
    imageSeed: 'half_arms_honey'
  },
  {
    id: 'wax-14',
    name: 'Half Arms Only (Rica Dark Chocolate Wax)',
    category: 'Waxing',
    price: 329,
    durationMinutes: 20,
    benefits: ['Glorious cocoa aroma', 'Silky hydration for modern active arms'],
    ingredients: ['Pure Dark chocolate cocoa base', 'Oils'],
    skinType: 'Dehydrated dry skins',
    procedure: ['Sanitize and prep', 'Spatula warm cream glide', 'Tension skin and pull strip', 'Rich almond oil post-massage'],
    aftercare: ['Apply SPF block if going out'],
    safety: ['Test inner wrist thermal sensitivity'],
    hygiene: ['Clean sanitized workspace setup'],
    imageSeed: 'half_arms_chocolate'
  },
  {
    id: 'wax-15',
    name: 'Underarms Only (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 119,
    durationMinutes: 10,
    benefits: ['Fast, effective odor removal assistance', 'Exfoliates underarm sweat area'],
    ingredients: ['Purified honey element', 'Concentrated Aloe extracts'],
    skinType: 'Normal skin',
    procedure: ['Dust pre-wax talc', 'Apply honey wax carefully', 'Flick strip', 'Soothing wipe'],
    aftercare: ['Deodorant restrictions for 24 hours'],
    safety: ['Carefully look for heat response'],
    hygiene: ['Spatulas safely disposed in trash bin'],
    imageSeed: 'underarms_honey'
  },
  {
    id: 'wax-16',
    name: 'Underarms Only (Rica Brazilian Wax)',
    category: 'Waxing',
    price: 189,
    durationMinutes: 15,
    benefits: ['Stops skin darkening', 'Grabs short stubborn hairs without stripping skin layer'],
    ingredients: ['Brazilian avocado and argan oils', 'Titanium compounds'],
    skinType: 'Highly sensitive skin types',
    procedure: ['Prep with avocado cleansing gel', 'Apply film thick wax patch', 'Peel directly without paper strip', 'Soothing rose serum'],
    aftercare: ['Avoid heavy sweat workouts'],
    safety: ['Ensure complete dry base before applying wax'],
    hygiene: ['Sanitary gloves changed right after service'],
    imageSeed: 'underarms_brazilian'
  },
  {
    id: 'wax-17',
    name: 'Full Arms, Half Legs & Underarm (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 659,
    durationMinutes: 50,
    benefits: ['Super complete essential combo', 'Moisturized glowing limbs'],
    ingredients: ['Honey extract', 'Aloe gel formula'],
    skinType: 'Normal to dry skin',
    procedure: ['Prep all elements', 'Step-by-step waxing application', 'Cleanup residues with warm towel'],
    aftercare: ['Apply cooling calming lotion'],
    safety: ['Monitor thermal comfort on different regions'],
    hygiene: ['Fresh linen sheets changed in front of buyer'],
    imageSeed: 'combo_honey_aloe'
  },
  {
    id: 'wax-18',
    name: 'Full Arms, Half Legs & Underarm (Rica Dark Chocolate Wax)',
    category: 'Waxing',
    price: 1099,
    durationMinutes: 50,
    benefits: ['Deep tan reduction skin-glow', 'Luxurious chocolatey wellness scent'],
    ingredients: ['Natural Cocoa powder', 'Glyceryl Rosinate', 'Sweet oil'],
    skinType: 'Dry and lifeless skin combo care',
    procedure: ['Sanitize and prep', 'Precise warm spatula chocolate glide', 'Post-wax soothing Rica oil massage'],
    aftercare: ['Avoid scrubbing for 48 hours'],
    safety: ['Ensure varicose check on legs'],
    hygiene: ['Disposable gloves used continuously'],
    imageSeed: 'combo_chocolate'
  },
  {
    id: 'wax-19',
    name: 'Full Arms, Half Legs & Underarm (Rica Roll-On Wax)',
    category: 'Waxing',
    price: 1299,
    durationMinutes: 45,
    benefits: ['Incredibly speedy service', 'Painless clean roll-on execution'],
    ingredients: ['Titanium Dioxide', 'Cera Alba'],
    skinType: 'Oily and normal skin types',
    procedure: ['Calming spray mist', 'Steady cartridge glide', 'Rapid pull', 'Aloe refreshing spray'],
    aftercare: ['Avoid immediate gym session', 'Stay hydrated'],
    safety: ['Strict roller tension adjustments'],
    hygiene: ['Sterilized roll-on unit nozzles'],
    imageSeed: 'combo_rollon'
  },
  {
    id: 'wax-20',
    name: 'Full Arms (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 359,
    durationMinutes: 25,
    benefits: ['Removes layers of dust & dead cells', 'Perfect hair-free arms with aloe glow'],
    ingredients: ['Honey', 'Aloe juice base'],
    skinType: 'Normal skin and dry arms',
    procedure: ['Prep with pre-wax mist', 'Warm wax application', 'Quick strip pull'],
    aftercare: ['Apply moisturizing lotion'],
    safety: ['Test temperature strictly'],
    hygiene: ['Disposable sheets and single-use spatula'],
    imageSeed: 'full_arms_honey'
  },
  {
    id: 'wax-21',
    name: 'Full Arms (Rica Dark Chocolate)',
    category: 'Waxing',
    price: 539,
    durationMinutes: 25,
    benefits: ['Tackles stubborn environmental tan', 'Rich deep aroma and skin-glow'],
    ingredients: ['Theobroma cocoa extract', 'Titanium diocide'],
    skinType: 'All skins, dry skin preferred',
    procedure: ['Prep skin surface', 'Apply thin even layer of dark chocolate', 'Strip application and firm pull'],
    aftercare: ['Apply SPF sun block', 'No scratching'],
    safety: ['Confirm user has no chocolate allergies'],
    hygiene: ['Spatula single discard'],
    imageSeed: 'full_arms_choc'
  },
  {
    id: 'wax-22',
    name: 'Full Legs (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 476,
    durationMinutes: 35,
    benefits: ['Soft and shiny legs', 'Minimizes strawberry legs appearance'],
    ingredients: ['Bees honey', 'Organic aloe leaf juice'],
    skinType: 'Normal/Dry skin',
    procedure: ['Pre-wash legs', 'Slab warm honey wax', 'Flick stripe firmly', 'Gently cleanse and apply soothing lotion'],
    aftercare: ['Wear loose trousers', 'Avoid scrubbing for 2 days'],
    safety: ['Avoid over-heating the wax'],
    hygiene: ['Individually wrapped disposable sheets'],
    imageSeed: 'full_legs_honey'
  },
  {
    id: 'wax-23',
    name: 'Full Legs (Rica Dark Chocolate)',
    category: 'Waxing',
    price: 659,
    durationMinutes: 35,
    benefits: ['Smooth deep moisturizing formula', 'Eliminates dry white skin patches'],
    ingredients: ['Cocoa paste and argan oil'],
    skinType: 'Very dry flaky leg skin',
    procedure: ['Prep leg surface', 'Spatula glide Rica chocolate', 'Firm strip peel', 'Rica lavender soothing oil finish'],
    aftercare: ['Do not swim in clorinated paths for 24h'],
    safety: ['Do not apply on open cuts'],
    hygiene: ['Sterilized spatula and metal wax heaters'],
    imageSeed: 'full_legs_choc'
  },
  {
    id: 'wax-24',
    name: 'Full Legs (Rica Roll-On Wax)',
    category: 'Waxing',
    price: 679,
    durationMinutes: 30,
    benefits: ['Exceeding speed with maximum precision', 'Unparalleled smooth outer finish'],
    ingredients: ['Patented plant resins', 'Olive oil base'],
    skinType: 'All hair colors and skin types',
    procedure: ['Spray sanitization', 'Uniform roller stroke', 'Immediate non-woven band removal'],
    aftercare: ['Keep moisturized with aloe serum'],
    safety: ['Cartridge roller speed monitoring'],
    hygiene: ['Fresh roll-on cartridge used each time'],
    imageSeed: 'full_legs_rollon'
  },
  {
    id: 'wax-25',
    name: 'Full Legs (Cirepil Roll-On)',
    category: 'Waxing',
    price: 849,
    durationMinutes: 30,
    benefits: ['Highly premium European leg indulgence', 'Pain-conscious formula removes finest root hair'],
    ingredients: ['Cirepil patented elastomer resins', 'Nutritive botanical extracts'],
    skinType: 'Extremely sensitive leg surfaces',
    procedure: ['Apply pre-wax soothing oil', 'Roll-on glide', 'Gentle fast peel', 'Finish massage with jasmine cooling essence'],
    aftercare: ['Wash with cool water only', 'Avoid harsh soaps'],
    safety: ['Check leg capillary vessel states first'],
    hygiene: ['Exclusive single-use client roller design'],
    imageSeed: 'full_legs_cirepil'
  },
  {
    id: 'wax-26',
    name: 'Bikini Wax (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 999,
    durationMinutes: 60,
    benefits: ['Complete personal cleanliness', 'Aloe cooling element reduces inflammation'],
    ingredients: ['Sugar paste', 'Aloe gel concentrate', 'Distilled Honey'],
    skinType: 'Standard sensitive groin skins',
    procedure: ['Cleanse area with sanitary wipes', 'Dust soft pediatric talk', 'Carefully apply small warm patches', 'Precise manual tension pull'],
    aftercare: ['Wear loose cotton innerwear', 'Wash area with fresh clean plain water only'],
    safety: ['Extremely careful temperature validation', 'No double wax application'],
    hygiene: ['Gloved technician', 'All single-use disposables', 'Total sanitation protocols'],
    imageSeed: 'bikini_honey'
  },
  {
    id: 'wax-27',
    name: 'Bikini Wax (Rica Brazilian Wax)',
    category: 'Waxing',
    price: 1299,
    durationMinutes: 60,
    benefits: ['Stops skin redness', 'Peelable hard wax film requires no strip, much less pain'],
    ingredients: ['Brazilian organic resins', 'Soothing botanical oils'],
    skinType: 'Extra sensitive bikini areas',
    procedure: ['Pre-depilatory wax oil protection', 'Lay warm thick Brazilian film patch', 'Peel directly opposite hair growth', 'Apply therapeutic anti-bump serum'],
    aftercare: ['Avoid sauna, bath tubs for 48 hours', 'Comfortable clothes'],
    safety: ['Verify patch thickness', 'Gently compress pulled area with fingers'],
    hygiene: ['Strict disposable set, therapist wears protective eyewear and mask'],
    imageSeed: 'bikini_brazilian'
  },
  {
    id: 'wax-28',
    name: 'Bikini Line (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 299,
    durationMinutes: 15,
    benefits: ['Clean hair-free visual swim line', 'Fast minimal pain session'],
    ingredients: ['Organic honey', 'Aloe Vera extracts'],
    skinType: 'All skins',
    procedure: ['Disinfect layout', 'Spatula precision glide along crease', 'Clean release', 'Wash and soothe'],
    aftercare: ['Avoid immediate tight jeans', 'Keep dry and calm'],
    safety: ['Keep thermal heat low and safe'],
    hygiene: ['Double sanitization before beginning'],
    imageSeed: 'bikini_line_honey'
  },
  {
    id: 'wax-29',
    name: 'Brazilian Waxing (Intimate Area - Rica Brazilian Wax)',
    category: 'Waxing',
    price: 299,
    durationMinutes: 20,
    benefits: ['Absolute privacy and professional comfort', 'Perfect smooth results on coarse hair'],
    ingredients: ['Rica specialized Brazilian oil', 'Cera beeswax'],
    skinType: 'Sensitive intimate regions',
    procedure: ['Draping and sanitizing', 'Careful heat application of hard film', 'Manual pull technique', 'Anti-fungal tea tree oil application'],
    aftercare: ['Apply clean aloe daily', 'Avoid intense activities for 24h'],
    safety: ['Always keep skin pulled tightly to prevent bruising'],
    hygiene: ['Strict medical-grade double gloving during whole process'],
    imageSeed: 'brazilian_intimate'
  },
  {
    id: 'wax-30',
    name: 'Full Body Waxing Combo (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 1099,
    durationMinutes: 100,
    benefits: ['Complete head-to-toe hair-free visual glow', 'High-value economy package', 'Purifying honey detox for total body skin'],
    ingredients: ['Sweet Honey', 'Soothing fresh Aloe leaf juice'],
    skinType: 'Normal body skin types',
    procedure: ['Full body cleansing', 'Sequence waxing (Arms, Underarms, Legs, Back, Stomach)', 'Refreshing soothing body spray wash'],
    aftercare: ['Avoid perfumed body sprays for 24 hours', 'Stay cool hydrated'],
    safety: ['Therapist dynamically monitors whole-body response'],
    hygiene: ['Fresh clean disposable bedsheets and towels provided in-room'],
    imageSeed: 'full_body_honey'
  },
  {
    id: 'wax-31',
    name: 'Full Body Waxing Combo (Rica Dark Chocolate & Rica Brazilian)',
    category: 'Waxing',
    price: 1899,
    durationMinutes: 100,
    benefits: ['Ultimate body pampering ritual', 'Aromatherapy stress release', 'Deep antioxidant skin tan clear'],
    ingredients: ['Natural Cocoa Butter', 'Brazilian Avocado extracts', 'Titanium diocide'],
    skinType: 'Dry and sun-tanned body skin',
    procedure: ['Rica luxury pre-wash', 'Smooth chocolate wax glide', 'Post-wax body massage with Rica almond oil'],
    aftercare: ['No steam room visit for 48 hours', 'Wear loose breathable clothing'],
    safety: ['Specialized heat mapping strictly performed'],
    hygiene: ['Individually packed sanitary kits split-open per client'],
    imageSeed: 'full_body_choc'
  },
  {
    id: 'wax-32',
    name: 'Full Body Waxing Combo (Rica Roll-On Wax)',
    category: 'Waxing',
    price: 1999,
    durationMinutes: 90,
    benefits: ['Ultra swift complete waxing', 'Unclutters pores completely', 'No sticky post-wax feeling left'],
    ingredients: ['Liquid plant resin formulas', 'Olive leaf oil'],
    skinType: 'All normal and sensitive skins',
    procedure: ['Roll-on system body coverage sweep', 'Painless clean pull', 'Soothe body with lavender oil mist'],
    aftercare: ['Keep body moisturized', 'Avoid tight fabrics'],
    safety: ['Manage consistent cartridge roll speed'],
    hygiene: ['Brand-new roll cartridges loaded per service'],
    imageSeed: 'full_body_rollon'
  },
  {
    id: 'wax-33',
    name: 'Full Body Waxing Combo (Cirepil Roll-On Wax)',
    category: 'Waxing',
    price: 2399,
    durationMinutes: 90,
    benefits: ['The absolute gold standard of luxury body waxing', 'French patented comfort formulation', 'Stunning skin glow with near-zero discomfort'],
    ingredients: ['Cirepil proprietary active resins', 'Royal soothing oil base'],
    skinType: 'Extremely delicate sensitive body skin',
    procedure: ['Luxury pre-wax oil prep', 'Roller glide application', 'Feather pull comfort technique', 'Deluxe post-care massage'],
    aftercare: ['Soothe with rich calamine daily', 'Avoid synthetic fabrics'],
    safety: ['Individual allergen checks prior to beginning'],
    hygiene: ['Fully sealed multi-cartridge kit utilized on single client'],
    imageSeed: 'full_body_cirepil'
  },
  {
    id: 'wax-34',
    name: 'Stomach Wax (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 379,
    durationMinutes: 15,
    benefits: ['Fine torso hair removal', 'Exfoliates midriff area nicely'],
    ingredients: ['Honey', 'Aloe juice juice juice'],
    skinType: 'Normal skins',
    procedure: ['Sanitize and apply', 'Firm strip press', 'Release and wipe'],
    aftercare: ['Avoid tight waistbands'],
    safety: ['Avoid belly-button area bruises'],
    hygiene: ['Spatula single discard'],
    imageSeed: 'stomach_honey'
  },
  {
    id: 'wax-35',
    name: 'Stomach Wax (Rica Dark Chocolate)',
    category: 'Waxing',
    price: 539,
    durationMinutes: 15,
    benefits: ['Glowy midriff finish', 'Rich moisturizing prevents dryness on belly'],
    ingredients: ['Rich cocoa compound', 'Vegetable oils'],
    skinType: 'Dry and tanned skin tummy',
    procedure: ['Gently cleanse belly area', 'Spatula glide warm dark chocolate', 'Rapid release and almond rub'],
    aftercare: ['Wear cotton tank tops'],
    safety: ['Verify belly scars state first'],
    hygiene: ['Sanitary tools only'],
    imageSeed: 'stomach_choc'
  },
  {
    id: 'wax-36',
    name: 'Stomach Wax (Rica Roll-On)',
    category: 'Waxing',
    price: 649,
    durationMinutes: 15,
    benefits: ['Ultra uniform stomach glide', 'No hot wax droplets spill risk'],
    ingredients: ['Aqueous resin base'],
    skinType: 'Sensitive stomach skin',
    procedure: ['Glide roll cartridge', 'Paper-strip pull', 'Aloe hydration mist'],
    aftercare: ['Soothe with fresh gel'],
    safety: ['Control pressure on abdominals'],
    hygiene: ['Sealed personal cartridge roller'],
    imageSeed: 'stomach_rollon'
  },
  {
    id: 'wax-37',
    name: 'Stomach Wax (Cirepil Roll-On)',
    category: 'Waxing',
    price: 759,
    durationMinutes: 15,
    benefits: ['Painless stomach peach fuzz wrap', 'French premium finish'],
    ingredients: ['Cirepil exclusive elastomer'],
    skinType: 'Extremely thin sensitive skin',
    procedure: ['Jasmine pre-oil spray', 'Roll cartridge glide', 'Smooth peel', 'Cirepil lotion massage'],
    aftercare: ['Air cooling, avoid heavy tight belts'],
    safety: ['Dynamic check of abdominal comfort'],
    hygiene: ['Full hygienic environment maintenance'],
    imageSeed: 'stomach_cirepil'
  },
  {
    id: 'wax-38',
    name: 'Back Waxing (Honey Aloe Vera Wax)',
    category: 'Waxing',
    price: 519,
    durationMinutes: 15,
    benefits: ['Deep clean sweat pores on back', 'Removes layers of dirt & fuzz'],
    ingredients: ['Purified Honey', 'Aloe calming juice'],
    skinType: 'Normal skins prone to sweat',
    procedure: ['Cleanse back surface with antiseptic', 'Smooth warm honey wax layer', 'Wide strip pull', 'Calming pack'],
    aftercare: ['Avoid dynamic back exercises to prevent sweat bumps', 'Avoid immediate hot spray back wash'],
    safety: ['Carefully check back acne cysts before starting'],
    hygiene: ['Fresh bed wraps and disinfected metal tools'],
    imageSeed: 'back_honey'
  },
  {
    id: 'wax-39',
    name: 'Back Waxing (Rica Dark Chocolate)',
    category: 'Waxing',
    price: 579,
    durationMinutes: 15,
    benefits: ['Stops post-wax back pimples', 'Brightening cocoa skin glow'],
    ingredients: ['Natural cocoa extracts', 'Sweet base oils', 'Beeswax'],
    skinType: 'Tanned dry back skin',
    procedure: ['Apply pre-wax lotion', 'Even dark chocolate spatula sweep', 'Firm removal', 'Post wax soothing butter massage'],
    aftercare: ['Do not apply dense comedogenic oils on back for 3 days'],
    safety: ['Avoid moles and skin tags'],
    hygiene: ['Disposable gloves and single-use spatula rules strictly applied'],
    imageSeed: 'back_choc'
  },
  {
    id: 'wax-40',
    name: 'Back Waxing (Rica Roll-On)',
    category: 'Waxing',
    price: 799,
    durationMinutes: 15,
    benefits: ['Fastest back grooming session', 'Zero wax spills on skin, fully uniform hair removal'],
    ingredients: ['Rica liquid gel', 'Soothing compounds'],
    skinType: 'Normal to oily skins',
    procedure: ['Antiseptic sweep', 'Quick roller application', 'Fast non-woven strip pull', 'Teatree spray'],
    aftercare: ['Avoid heavy sweat workouts for 24h'],
    safety: ['Confirm user has no back injury'],
    hygiene: ['Sterile roller cartridge used once'],
    imageSeed: 'back_rollon'
  },
  {
    id: 'wax-41',
    name: 'Back Waxing (Cirepil Roll-On)',
    category: 'Waxing',
    price: 779,
    durationMinutes: 15,
    benefits: ['Absolute luxury back comfort package', 'Soft velvety finish without red inflammation bumps'],
    ingredients: ['Cirepil patented Elastomer', 'Jasmine extracts'],
    skinType: 'Highly sensitive skin back areas',
    procedure: ['Prep back with rose water mist', 'Smooth roller application', 'painless pull tech', 'Lavender essence rub'],
    aftercare: ['Soothe with calming hydrating emulsion'],
    safety: ['Check skin sensitivity on back spine'],
    hygiene: ['Double glove standard with sealed sanitary setup'],
    imageSeed: 'back_cirepil'
  },

  // --- FACIAL DETAILS ---
  {
    id: 'facial-1',
    name: 'Korean Glass Skin Facial',
    category: 'Facial & Cleanup',
    price: 1799,
    durationMinutes: 80,
    benefits: ['Provides the viral translucent glass-glow', 'Intensely hydrated plumbing effect', 'Evens skin discoloration', 'Boosts natural collagen synthesis'],
    ingredients: ['Centella Asiatica (Cica)', 'Hyaluronic Acid molecules', 'Niacinamide (B3)', 'Ginseng active root extract'],
    skinType: 'All skin types, especially dehydrated, dry or weary skin',
    procedure: ['Double cleansing with K-oil & water foam cleanser', 'Exfoliating enzyme peel pack application', 'Ultrasonic hydration serum infusion', 'Hydro-jelly skin-soothing glass sheet mask', 'Niacinamide barrier sealing cream massage'],
    aftercare: ['No makeup or face wash for next 12 hours', 'Apply high SPF 50 block next morning without fail', 'Keep skin heavily moisturized'],
    safety: ['Avoid active severe cystic acne zones during mechanical infusion', 'Keep skin hydrated'],
    hygiene: ['Sterilized ultrasonic probe before customer visit', 'Surgical gloves, sterilized mixing bowls'],
    imageSeed: 'korean_glass'
  },
  {
    id: 'facial-2',
    name: 'K-Glass Glow Cleanup',
    category: 'Facial & Cleanup',
    price: 799,
    durationMinutes: 50,
    benefits: ['Quick, instant boost of dewiness', 'Deep pore cleaning with K-beauty aesthetic'],
    ingredients: ['Hyaluronic Acid', 'Cherry blossom extracts', 'Vitamin C active'],
    skinType: 'Dull, dry and oily skin types search of quick radiance',
    procedure: ['Gentle rice-water wash', 'Hydrating exfoliation scrub', 'High concentration glass glow serum massage', 'Cooling hydro-pack overlay'],
    aftercare: ['Avoid direct intense heat source immediately', 'Use cool botanical mist'],
    safety: ['Avoid vigorous scrubbing around tender lips and nose edges'],
    hygiene: ['Fresh head-band used per client', 'Individually disinfected tools used only'],
    imageSeed: 'korean_glow_cleanup'
  },
  {
    id: 'facial-3',
    name: 'VLCC Fruit Facial',
    category: 'Facial & Cleanup',
    price: 799,
    durationMinutes: 60,
    benefits: ['Organic fruit enzymes gently clarify skin pores', 'Natural AHA actions remove tanning', 'Refreshing natural fruity glow'],
    ingredients: ['Papaya enzyme (Papain)', 'Watermelon soothing minerals', 'Apple fruit extract', 'Peach micro-scrub particles'],
    skinType: 'Normal, Oily and Combination skin types',
    procedure: ['VLCC deep pore cleanser', 'Papaya enzyme seed exfoliating massage', 'Hydrating peach massage cream skin therapy', 'Fruity multi-vitamin peel mask application', 'Fresh watermelon hydrating toner spray'],
    aftercare: ['No harsh soaps or scrubs on face for 48 hours', 'Wash face with cool plain water only'],
    safety: ['Confirm client is not allergic to natural tropical fruits'],
    hygiene: ['Fresh sterilized bowls to mix fruit packs', 'Technician sanitizes hands under client gaze'],
    imageSeed: 'vlcc_fruit'
  },
  {
    id: 'facial-4',
    name: 'Aroma Magic Pearl Facial',
    category: 'Facial & Cleanup',
    price: 999,
    durationMinutes: 70,
    benefits: ['Pearl dust provides shimmering skin fairness radiance', 'Repairs damaged skin cells deep within', 'Deep detox action'],
    ingredients: ['Active Pearl Dust powder', 'Essential oils of Rose and Sandalwood', 'Kaolin clay base'],
    skinType: 'Tanned, pigmented and uneven skin tones',
    procedure: ['Double wash with chamomile sanitizer', 'Elegantly gently scrub with Pearl Enzyme gel', 'Pure massage with nourishing Pearl cream', 'Apply Pearl mud hydration pack', 'Friction skin closing therapy'],
    aftercare: ['Avoid immediate sweating or cooking near gas-stoves', 'Keep face dabbed with cold chamomile water'],
    safety: ['Slight tingle due to mineral clay is normal; stop if intense burning felt'],
    hygiene: ['Single-use Aroma Magic salon tubes only', 'Sterile fresh beauty towels used'],
    imageSeed: 'aroma_pearl'
  },
  {
    id: 'facial-5',
    name: 'Gold Facial (Elegant Glow Edition)',
    category: 'Facial & Cleanup',
    price: 1149,
    durationMinutes: 70,
    benefits: ['Premium 24K gold foil particles activate cellular metabolism', 'Incredible sparkling festive gold glow', 'Locks skin hydration layers'],
    ingredients: ['Colloidal Gold particles', 'Wheatgerm oil', 'Saffron (Kesar) extracts', 'Sandalwood extract powder'],
    skinType: 'Normal, dry, mature, and wedding/festive prepped skins',
    procedure: ['Gold gel skin cleansing activity', 'Luxury gold dust micro-exfoliation', 'Restorative gold cream deep tissue massage (15 mins)', 'Apply premium 24K Gold peel-off mask', 'Gold face serum locking massage'],
    aftercare: ['Strictly no bleach or scrub application on face for 72 hours', 'Avoid makeup for 24h'],
    safety: ['Check dynamic capillary response during gold cream massage', 'Do not use over high skin eczema'],
    hygiene: ['Brand-new gold pack opened directly before user', 'Sterilized spa room bedding'],
    imageSeed: 'gold_facial'
  },
  {
    id: 'facial-6',
    name: 'Japanese Cherry Blossom Facial',
    category: 'Facial & Cleanup',
    price: 1199,
    durationMinutes: 90,
    benefits: ['Intense pink glow radiance', 'Soothes inflammation completely', 'Provides wonderful antioxidant therapy and fresh feel'],
    ingredients: ['Japanese Sakura Cherry Blossom leaf extract', 'White mulberry skin lightener', 'Hyaluronic base'],
    skinType: 'All skins, exceptionally beautiful on sensitive skins',
    procedure: ['Cleansing with Sakura foam wash', 'Sakura microcrystalline rice-bran scrub', 'Cherry Blossom glowing face cream massage', 'Sakura clay anti-stress therapy mask', 'Petal spray toner finish'],
    aftercare: ['Avoid soap or chemical washes for 24 hours', 'Keep hydrated with cool water'],
    safety: ['Keep eyes closed securely during clay therapy application'],
    hygiene: ['All natural cosmetic tubes opened fresh', 'Linen disinfected with lavender sanitizer'],
    imageSeed: 'cherry_blossom'
  },
  {
    id: 'facial-7',
    name: 'FYC Antioxidant Wine Facial',
    category: 'Facial & Cleanup',
    price: 1259,
    durationMinutes: 70,
    benefits: ['Resveratrol rich antioxidants counter free radicals', 'Superb anti-aging wrinkle defense', 'Tightens skin texture and boosts glow'],
    ingredients: ['Red Wine seed extract', 'Grapevine polyphenols', 'Pomegranate fruit extract', 'Aloe vera gel'],
    skinType: 'Dull, aging, sagging, and pollution exposed skin types',
    procedure: ['Wash with antioxidant grape-cleanser', 'Red wine scrub circular massage (10 mins)', 'Nourishing wine cream face lifting strokes', 'Wine infusion gel pack therapy', 'Cool tea-tree compression'],
    aftercare: ['No scrubbing for 3 days', 'Apply cool facial mist to lock grape nutrients'],
    safety: ['Check wine ingredients compatibility with skin elasticity'],
    hygiene: ['Sterilized massage spatulas and high-hygiene facial rollers used only'],
    imageSeed: 'wine_facial'
  },
  {
    id: 'facial-8',
    name: 'O3+ D Facial (Deep Cleanse & Exfoliation)',
    category: 'Facial & Cleanup',
    price: 1559,
    durationMinutes: 70,
    benefits: ['Premium dermatologically studied O3+ treatment', 'Unblocks deeply embedded blackheads', 'Soothes dermal inflammation blocks'],
    ingredients: ['Oxygenated formulation factors', 'Tea Tree extract oil', 'Salicylic trace compound', 'Menthol cool-capsules'],
    skinType: 'Severely tanned, oily, blackhead-prone skin types',
    procedure: ['O3+ D-tan face wash', 'Deep pore extraction with steam (5 mins)', 'Surgical blackhead extractor tool use (gentle)', 'Anti-microbial cooling gel massage', 'O3+ pore tight oxygen mask'],
    aftercare: ['Do not touch nose blackhead area', 'No squeezing skin at home', 'Apply cooling tea tree gel'],
    safety: ['Do not use heavy pore steam on broken vascular thread veins'],
    hygiene: ['Stainless steel comedone extractors strictly autoclaved and disinfected'],
    imageSeed: 'o3plus_d'
  },
  {
    id: 'facial-9',
    name: 'O3+ Shine & Glow Facial',
    category: 'Facial & Cleanup',
    price: 1599,
    durationMinutes: 80,
    benefits: ['Provides the elite high-shine salon glow', 'Evens skin discoloration', 'Brightens tired skin layers'],
    ingredients: ['Vitamin C complex', 'Arbutin brightener', 'Licorice root active extract'],
    skinType: 'Pre-bride, party prepped, normal to dry skins',
    procedure: ['Deep O3+ Shine milk cleanse', 'Micro-scrub shine face peel', 'Radiance massage gel application', 'Luxury O3+ sheet lock pack mask', 'Shine serum drops patting'],
    aftercare: ['No steam room visit, avoid chlorinated pools', 'Use clean silk pillowcover at night'],
    safety: ['Avoid getting active serum inside client eyes'],
    hygiene: ['Surgical-grade face wipes only', 'Headband fully washed with steam disinfected laundry'],
    imageSeed: 'o3plus_shine'
  },
  {
    id: 'facial-10',
    name: 'Sara Vitamin C Cleanse',
    category: 'Facial & Cleanup',
    price: 749,
    durationMinutes: 45,
    benefits: ['Fades dark spots and hyperpigmentation', 'Provides immediate citric freshness to facial skin'],
    ingredients: ['L-ascorbic acid (Vitamin C)', 'Orange peel essential oil', 'Lemon extracts'],
    skinType: 'All skins, exceptionally effective on blemished oily skin',
    procedure: ['Vitamin C milk wash', 'Sara gentle citric scrub down', 'Vitamin C active booster massage', 'Brightening citrus cream pack seal'],
    aftercare: ['Apply SPF 30+ immediately before walking into daylight'],
    safety: ['Slight natural tingling with Vitamin C is normal; discontinue if rash appears'],
    hygiene: ['Fresh paper tissues, single-use applicators used strictly'],
    imageSeed: 'sara_vit_c'
  },
  {
    id: 'facial-11',
    name: 'Aroma Magic Fruit Clean Up',
    category: 'Facial & Cleanup',
    price: 799,
    durationMinutes: 50,
    benefits: ['Expels pore dirt and environmental pollution debris', 'Nourishes with pure essential botanical oils'],
    ingredients: ['Pure Apple extract', 'Avocado butter extract', 'Lavender essential oils'],
    skinType: 'All normal, dry, and sensitive skins',
    procedure: ['Aroma cleansing gel wash', 'Aroma magic jojoba seed scrub massage', 'Fruit soothing pack application', 'Refreshing rose tonic splash'],
    aftercare: ['Avoid using heavy synthetic makeup immediately after cleanup'],
    safety: ['Check user for sensitivity towards plant extracts'],
    hygiene: ['Disinfected face brushes and sanitized massage space'],
    imageSeed: 'aroma_fruit_cleanup'
  },
  {
    id: 'facial-12',
    name: 'Raga Rejuvenating Cleanup',
    category: 'Facial & Cleanup',
    price: 699,
    durationMinutes: 45,
    benefits: ['Restores moisture to tired facial cells', 'Calming and cooling visual impact'],
    ingredients: ['Vitamins E & A', 'Wheat germ oil extract', 'Seaweed mineral elements'],
    skinType: 'Dehydrated and weary skin types needing fast energy',
    procedure: ['Raga revitalizing wash', 'Soft enzyme scrub facial massage', 'Calming mineral algae pack', 'Toning water spray'],
    aftercare: ['Apply moisturizing face cream daily'],
    safety: ['Do not apply on dynamic sunburn rashes'],
    hygiene: ['Fresh bed wrapper and sanitized therapist gloves'],
    imageSeed: 'raga_rejuvenating'
  },
  {
    id: 'facial-13',
    name: 'Raga Revitalizing Cleanup',
    category: 'Facial & Cleanup',
    price: 699,
    durationMinutes: 45,
    benefits: ['Brightens tired eyes and face zones', 'Cleans oil and grease instantly'],
    ingredients: ['Mint oil leaf', 'Sea weed minerals', 'Zinc base oxide'],
    skinType: 'Coarse, greasy combination skin types',
    procedure: ['Deep mint wash', 'Zinc-oxide pore cleanup scrub', 'Raga revitalizing botanical mask', 'Mint toner finish'],
    aftercare: ['Stay hydrated with fresh juices', 'Avoid heavy sun'],
    safety: ['Keep cooling mint mask far from delicate lower eye rims'],
    hygiene: ['Steam cleaned cotton facial swabs used only'],
    imageSeed: 'raga_revitalizing'
  },

  // --- MANICURES & PEDICURES ---
  {
    id: 'nail-1',
    name: 'Nail Cut, File & Polish (Manicure)',
    category: 'Manicure & Pedicure',
    price: 189,
    durationMinutes: 15,
    benefits: ['Neat beautifully shaped nails', 'Premium shine enamel finish'],
    ingredients: ['Organic cuticle oil', 'Nail protein coat base', 'Vitamin E oil'],
    skinType: 'All nail conditions',
    procedure: ['Trim nails with sanitized clipper', 'Precision shaping with high grade emery file', 'Buff nail plates', 'Moisturize cuticle', 'Double coat polish application'],
    aftercare: ['Let nail polish dry fully (15 mins)', 'Do not submerge nails in soapy water immediately'],
    safety: ['Sterilize clippers before starting', 'No aggressive cuticle cutting'],
    hygiene: ['Tools sterilized with medical autoclave', 'Disposable file buffer'],
    imageSeed: 'cut_file_manicure'
  },
  {
    id: 'nail-2',
    name: 'Aroma Magic Lemon Manicure',
    category: 'Manicure & Pedicure',
    price: 709,
    durationMinutes: 15,
    benefits: ['Natural citric bleaching properties brightens fingers', 'Eradicates tanning on finger joints', 'Delightful uplifting zesty scent'],
    ingredients: ['Lemon essential oil paste', 'Sea salt scrub crystals', 'Sweet orange nourishing massage butter'],
    skinType: 'Dull, tanned, dry skins on arms & hands',
    procedure: ['Lemon hand soak bath', 'Cuticle trimming & nail shaping prep', 'Aromatic lemon hand sugar scrub exfoliation', 'Elegantly therapeutic hand massage (10 mins)', 'Brightening hand cream wrap'],
    aftercare: ['Do not expose hands to harsh dishwashing soap for 24h', 'Apply hand lotion'],
    safety: ['Avoid soaking hands if there is any active scratch/paper cut'],
    hygiene: ['Sanitized pedicure tub wrapper', 'Fresh warm distilled water with lemon slices'],
    imageSeed: 'aroma_manicure'
  },
  {
    id: 'nail-3',
    name: 'Korean Manicure by FYC',
    category: 'Manicure & Pedicure',
    price: 1099,
    durationMinutes: 65,
    benefits: ['Extremely premium K-beauty styling session', 'Deep epidermal hand hydration', 'Silky luxury skin feel on hands'],
    ingredients: ['Ginseng root oil', 'Ceramides', 'Collagen peptides'],
    skinType: 'All hand skins, exceptionally good for dry parched skin',
    procedure: ['Warm collagen serum hand bath soak', 'Ultra refined nail filing and cuticle care', 'Ginseng active hand scrub peeling', 'Nourishing botanical ceramide mask application', 'Therapeutic hot stone hand relaxation massage'],
    aftercare: ['Nourish daily with rich hand butter'],
    safety: ['Monitor thermal state of hot stone strictly'],
    hygiene: ['Medical grade sanitization of stainless steel pusher and nippers'],
    imageSeed: 'korean_manicure'
  },
  {
    id: 'nail-4',
    name: 'D-Tan Manicure',
    category: 'Manicure & Pedicure',
    price: 849,
    durationMinutes: 55,
    benefits: ['Removes persistent sun-tanning from hands', 'Moisturizes dry cuticles, heals nail ridges'],
    ingredients: ['Licorice extract', 'Kojic acid factors', 'Lactic milk enzymes'],
    skinType: 'All deeply sun-tanned hand skin types',
    procedure: ['Lactic soap soak bubble bath', 'Nail shaping & buffing prep', 'Apply D-tan professional hand pack (10 mins)', 'Remove pack with dual massage clean', 'Soothing hand lotion seal'],
    aftercare: ['Wear protective hand gloves when doing housework with chemicals'],
    safety: ['Ensure no open cuts on fingers before applying active D-tan pack'],
    hygiene: ['Exclusive single-use disposable manicuring towel'],
    imageSeed: 'dtan_manicure'
  },
  {
    id: 'nail-5',
    name: 'Dead Sea Manicure by AVL',
    category: 'Manicure & Pedicure',
    price: 949,
    durationMinutes: 55,
    benefits: ['Dead Sea therapeutic salts detoxify hand cells', 'Excellent mineral-based joint relaxation', 'Unparalleled smooth finish'],
    ingredients: ['Dead Sea raw mineral salt', 'Magnesium chlorides', 'Tea tree essential oil extract'],
    skinType: 'Rheumatic stiff joints on hands/fingers, very dry skin',
    procedure: ['Dead Sea mineral warm hand soak bath', 'Deep cuticle sanitization & nail prep', 'Mineral sea-salt scrub rub', 'Nourishing hand mud paste wrapping', 'Aromatic cooling massage'],
    aftercare: ['Avoid immediately washing hands with synthetic soap gels'],
    safety: ['Ensure salt mask does not enter microscopic skin cracks'],
    hygiene: ['Fully autoclaved tools and individually unpackaged single basin liners'],
    imageSeed: 'dead_sea_manicure'
  },
  {
    id: 'nail-6',
    name: 'Nail Cut, File & Polish (Pedicure)',
    category: 'Manicure & Pedicure',
    price: 239,
    durationMinutes: 15,
    benefits: ['Keeps feet clean, neat, and hygienic', 'Shapes toenails beautiful visual finish'],
    ingredients: ['Anti-fungal pine oil', 'Lanolin skin hydrate', 'Vitamin E oil'],
    skinType: 'All feet nails',
    procedure: ['Toenail trim, visual edge filing', 'Buff toenail surface', 'Nail plate debris clean', 'Slight moisturizing heel rub', 'Double layer premium polish coat'],
    aftercare: ['Wear open-toed sandals or flip-flops immediately for polish safety'],
    safety: ['Strict caution around deep ingrown toe nail edges'],
    hygiene: ['Auto-claved clippers, disposable wooden orange nail sticks used strictly'],
    imageSeed: 'cut_file_pedicure'
  },
  {
    id: 'nail-7',
    name: 'Therapeutic Foot Massage',
    category: 'Manicure & Pedicure',
    price: 199,
    durationMinutes: 10,
    benefits: ['Improves blood circulation on feet and heels', 'Eases walking muscle aches instantly', 'Promotes sound sleep'],
    ingredients: ['Camphor oil extract', 'Peppermint oil energy', 'Menthol rub base'],
    skinType: 'Tired, heavy, aching feet muscular structures',
    procedure: ['Warm foot wipe cleansing', 'Apply mint-infused cooling therapeutic foot balm', 'Reflexology joint pressure-points thumb stroke massage', 'Hot towel wipe clean'],
    aftercare: ['Drink a warm glass of water', 'Keep feet warm directly afterwards'],
    safety: ['Strict caution for pregnant clients (reflexology pressure point checks)'],
    hygiene: ['Clean sanitized towel wraps, therapist sanitizes hands with antiseptic'],
    imageSeed: 'foot_massage'
  },
  {
    id: 'nail-8',
    name: 'Korean Pedicure by FYC',
    category: 'Manicure & Pedicure',
    price: 1599,
    durationMinutes: 75,
    benefits: ['Aesthetic K-Beauty foot healing ritual', 'Exfoliates thick calluses and hard cracked dry heels', 'Deep cellular hydration'],
    ingredients: ['Bamboo extract charcoal', 'Ginseng powder root', 'Snail mucin healing factors', 'Shea butter'],
    skinType: 'Dry, extremely cracked heels and calloused feet surfaces',
    procedure: ['Warm water lavender charcoal bubble soak', 'Deep callus scrape with sterilized rasp scraper', 'Toenail edge sculpting & cuticle clearing', 'Ginseng active smoothing foot scrub massage (15 mins)', 'Hot stone feet massage', 'Snail mucin hydration pack'],
    aftercare: ['Wear cotton foot socks at night paired with moisturizing heel cream'],
    safety: ['Painless rasp scraper usage with experienced visual guidance'],
    hygiene: ['Sanitized pedicure basin with medical grade plastic liner changed per customer'],
    imageSeed: 'korean_pedicure'
  },
  {
    id: 'nail-9',
    name: 'Aroma Magic Lemon Pedicure',
    category: 'Manicure & Pedicure',
    price: 759,
    durationMinutes: 65,
    benefits: ['Purifies sweat glands of ankles and feet', 'Deeply bleached tan clearance', 'Refreshing, uplifting aromatherapy wellness'],
    ingredients: ['Fresh Lemon juice extracts', 'Aromatic rosemary leaf oil', 'Sorbic acid salt scrub'],
    skinType: 'Sweaty feet, bad odor issues, tanned ankles',
    procedure: ['Warm double strength lemon foot bath soak', 'Professional pedicure nail trim and heel clean', 'Rosemary sugar feet and ankle scrub massage', 'Soft lemon cooling massage cream rub', 'Clay anti-odor feet pack'],
    aftercare: ['Use open visual footwear to allow fresh ventilation for feet'],
    safety: ['Avoid applying rich citrus scrub over cracked open bleeding heel cracks'],
    hygiene: ['Clean single-use basin setup with lemon slices discarded after service'],
    imageSeed: 'aroma_pedicure'
  },
  {
    id: 'nail-10',
    name: 'D-Tan Pedicure',
    category: 'Manicure & Pedicure',
    price: 849,
    durationMinutes: 65,
    benefits: ['Evens intense flip-flop tan lines on feet', 'Gently conditions tough foot structures, hydrates toe cuticles'],
    ingredients: ['Morus Alba (Mulberry) extract', 'Lactic enzymes', 'Avocado butter extract'],
    skinType: 'Tanned, parched, dust-exposed feet skin',
    procedure: ['Saponified milk bubble warm feet soak', 'Heel scraping and toenail grooming', 'Apply D-tan milk formulation foot wrap (15 mins)', 'Remove wrap with circular scrub down', 'Cold water splash and massage gel'],
    aftercare: ['Apply feet creams daily before sleeping'],
    safety: ['No heavy chemicals on open wounds'],
    hygiene: ['Exclusive disinfected rasp files and fresh disposable foot basin liners'],
    imageSeed: 'dtan_pedicure'
  },
  {
    id: 'nail-11',
    name: 'Dead Sea Pedicure by AVL',
    category: 'Manicure & Pedicure',
    price: 999,
    durationMinutes: 65,
    benefits: ['Deep therapeutic relief from Dead Sea mineral salts', 'Excellent visual cure for tired ankle joints and heel pains', 'Smooth soft skin outcomes'],
    ingredients: ['Dead Sea coarse sea salt minerals', 'Eucalyptus leaf extract essential oil', 'Shea butter hydration cream'],
    skinType: 'Heel pain sufferers, deeply scaling dry skin feet',
    procedure: ['Dead Sea eucalyptus warm foot soak', 'Toenail shaping & foot rasp heel cleaning', 'Dead Sea mineral salt scrub exfoliation', 'Dead Sea therapeutic mineral mud foot pack wrap', 'Shea butter premium foot massage'],
    aftercare: ['Apply moisturizing defense cream daily'],
    safety: ['Strict dynamic temperature validation for the warm soak'],
    hygiene: ['Hospital grade disinfected tools and fresh disposable components'],
    imageSeed: 'dead_sea_pedicure'
  },

  // --- THREADING & FACE WAX ---
  {
    id: 'thread-1',
    name: 'Eyebrows (Premium Cotton Threading)',
    category: 'Threading & Face Wax',
    price: 49,
    durationMinutes: 10,
    benefits: ['Symmetrical, sharp defined visual brow shapes', 'Extremely neat outline frame with zero fluff hair'],
    ingredients: ['Premium organic cotton thread', 'Antiseptic cooling rose water', 'Soothing fresh aloe vera leaf gel'],
    skinType: 'All skin types around eyebrows',
    procedure: ['Assess facial bone contour with client preferences', 'Dust hygienic talc powder safely with eyes shut', 'Apply dynamic cotton thread loop threading technique', 'Soothing lavender and aloe vera massage'],
    aftercare: ['Do not apply dense foundation makeup on brow area for 12 hours', 'Avoid direct sun face exposure'],
    safety: ['Keep eyes safe and closed, skin around brows held tight by user'],
    hygiene: ['Surgical-grade premium antiseptic thread rolls used fresh for each brow session'],
    imageSeed: 'eyebrows_threading'
  },
  {
    id: 'thread-2',
    name: 'Upper Lip (Hygienic Thread)',
    category: 'Threading & Face Wax',
    price: 49,
    durationMinutes: 10,
    benefits: ['Removes shadow-causing hair on upper lip', 'Smooth, glowing base for fine visual lipstick prep'],
    ingredients: ['Surgical-grade antiseptic thread', 'Tea tree cooling toner'],
    skinType: 'All skin types',
    procedure: ['Client supports tight skin with tongue internally', 'Apply swift fine threading line', 'Soothe with tea tree gel and calamine'],
    aftercare: ['Avoid using heavy citrus clean face products for 12 hours'],
    safety: ['Precise loop control to prevent pinching sensitive lip corners'],
    hygiene: ['Towel changed, thread single discard'],
    imageSeed: 'upperlip_threading'
  },
  {
    id: 'thread-3',
    name: 'Forehead Threading',
    category: 'Threading & Face Wax',
    price: 59,
    durationMinutes: 10,
    benefits: ['Exfoliates dead forehead dandruff debris', 'Leaves forehead clean and beautifully framed'],
    ingredients: ['Pure cotton thread', 'Witch hazel cooling toner'],
    skinType: 'All skins',
    procedure: ['Dust forehead with talc', 'Swift threading rows', 'Wipe with calming witch hazel mist'],
    aftercare: ['Avoid dynamic scrubbing of forehead for 1 day'],
    safety: ['Secure hair back safely out of threading fields'],
    hygiene: ['Therapist sanitizes forehead area cleanly first'],
    imageSeed: 'forehead_threading'
  },
  {
    id: 'thread-4',
    name: 'Full Face Threading (Forehead, Brows, Cheek, Chin, Jaw)',
    category: 'Threading & Face Wax',
    price: 149,
    durationMinutes: 30,
    benefits: ['Complete fuzz-free facial skin radiance', 'Ideal base layout for stunning bridal makeup matches'],
    ingredients: ['Clean antiseptic thread', 'Rose extract lotion', 'Pure Aloe leaf gel'],
    skinType: 'Normal, dry, and combination skins',
    procedure: ['Cleanse face with witch hazel water', 'Sequential threading: Forehead to Brows to Cheeks to Lip & Chin', 'Relaxing soothing face massage (5 mins) with Aloe Vera and ice compression'],
    aftercare: ['Restrict face scrubbing, direct hot steam, and dense cosmetics for 24 hours'],
    safety: ['Hold skin securely tight to prevent thread bites'],
    hygiene: ['Fresh sterilized towels, hair bands and brand new sterile thread reel segment'],
    imageSeed: 'full_face_threading'
  },
  {
    id: 'thread-5',
    name: 'Side Locks Threading',
    category: 'Threading & Face Wax',
    price: 49,
    durationMinutes: 10,
    benefits: ['Removes dark side fuzz shadows', 'Gives sharp linear visual shape to hairline'],
    ingredients: ['Pure thread', 'Ice compression water'],
    skinType: 'All skins',
    procedure: ['Hold ear side skin taut', 'Painless micro thread strokes', 'Apply calming ice cream cube'],
    aftercare: ['Avoid immediate scratching'],
    safety: ['Never pull thread too deep near active side acne'],
    hygiene: ['Therapist wears fresh disinfected gloves'],
    imageSeed: 'sidelocks_threading'
  },
  {
    id: 'thread-6',
    name: 'Chin Hair Threading',
    category: 'Threading & Face Wax',
    price: 29,
    durationMinutes: 10,
    benefits: ['Roots out tough chin stubble hair follicles', 'Prevents skin scarring from tweezing'],
    ingredients: ['Organic cotton thread', 'Chamomile soothing gel'],
    skinType: 'Normal and acne prone chin skins',
    procedure: ['Sanitize chin skin', 'Fast thread loop capture', 'Clean wipe with chamomile'],
    aftercare: ['Keep area free of greasy heavy foundations for 12 hours'],
    safety: ['Always tension chin bone skin carefully'],
    hygiene: ['Hygienic face tools only'],
    imageSeed: 'chin_threading'
  },
  {
    id: 'thread-7',
    name: 'Jawline Threading',
    category: 'Threading & Face Wax',
    price: 99,
    durationMinutes: 10,
    benefits: ['Removes shadows along jawline profile', 'Defines face structure visuals beautifully'],
    ingredients: ['Soothe aloe essence'],
    skinType: 'All skins',
    procedure: ['Tension jaw skin', 'Thread fuzz away', 'Spray cooling water mist'],
    aftercare: ['No dry scrubbing'],
    safety: ['Check for jaw skin tags'],
    hygiene: ['Sterilized thread segments'],
    imageSeed: 'jawline_threading'
  },
  {
    id: 'thread-8',
    name: 'Upper Lip Face Wax (Sensitive Peelable Honey Wax)',
    category: 'Threading & Face Wax',
    price: 59,
    durationMinutes: 10,
    benefits: ['Much faster, less painful than threading on sensitive lips', 'Keeps lip area soft and clear'],
    ingredients: ['Hard peelable aloe wax film', 'Chamomile cooling oil'],
    skinType: 'Highly sensitive skin types',
    procedure: ['Pre-wax skin oil shield', 'Apply tiny warm wax film directly on upper lip', 'Gently peel without any strip paper', 'Calamine calming touch'],
    aftercare: ['No scrubbing around nose or mouth area for 1 day'],
    safety: ['Dynamic check of wax heating levels', 'Do not stretch lip tissue too hard'],
    hygiene: ['Single use specialized spatulas discarded immediately'],
    imageSeed: 'upperlip_wax'
  },
  {
    id: 'thread-9',
    name: 'Chin Face Waxing',
    category: 'Threading & Face Wax',
    price: 89,
    durationMinutes: 10,
    benefits: ['Removes deep roots completely with near-zero itching post-care'],
    ingredients: ['Hydrating hard wax', 'Almond extract oil'],
    skinType: 'All skins with chin stubble',
    procedure: ['Sanitize and wipe chin', 'Lay safe warm wax film', 'Peel directly', 'Massage with soothing tea tree cream'],
    aftercare: ['Avoid touching face skin'],
    safety: ['Strict check on thermal threshold'],
    hygiene: ['Disposable gloves changed post service'],
    imageSeed: 'chin_wax'
  },
  {
    id: 'thread-10',
    name: 'Lower Lip Face Waxing',
    category: 'Threading & Face Wax',
    price: 59,
    durationMinutes: 10,
    benefits: ['Quick, painless below lip fuzz elimination', 'Gives clean gorgeous lip glow'],
    ingredients: ['Premium honey beeswax'],
    skinType: 'All skins',
    procedure: ['Dab with talc, glide warm wax paper', 'Quick pull', 'Soothing balm'],
    aftercare: ['Avoid active dynamic lip scrubs'],
    safety: ['Low temperature limit'],
    hygiene: ['Sterile spatula uses only'],
    imageSeed: 'lowerlip_wax'
  },
  {
    id: 'thread-11',
    name: 'Side Locks Face Waxing',
    category: 'Threading & Face Wax',
    price: 89,
    durationMinutes: 10,
    benefits: ['Sleek smooth sidelocks for gorgeous hairdo visuals'],
    ingredients: ['Teatree extract hard wax', 'Oils'],
    skinType: 'All skins',
    procedure: ['Prep sideline skin, lay hot film wax', 'Painless peel', 'Soothing tea tree scrub clean'],
    aftercare: ['Avoid heavy sweat workouts'],
    safety: ['Do not apply too close to scalp hairline'],
    hygiene: ['Disinfected space and tools'],
    imageSeed: 'sidelocks_wax'
  },
  {
    id: 'thread-12',
    name: 'Jawline Face Waxing',
    category: 'Threading & Face Wax',
    price: 89,
    durationMinutes: 10,
    benefits: ['Saves time, keeps lower jaw outline totally clean'],
    ingredients: ['Brazilian organic film wax'],
    skinType: 'All skins',
    procedure: ['Sanitizing jaw, wax brush stroke, swift manual peel', 'Cool lavender massage'],
    aftercare: ['Keep area free of dense greasy cosmetics'],
    safety: ['Verify user does not have neck gland swelling'],
    hygiene: ['Sanitized room and tools'],
    imageSeed: 'jawline_wax'
  },
  {
    id: 'thread-13',
    name: 'Neck Face Waxing',
    category: 'Threading & Face Wax',
    price: 179,
    durationMinutes: 15,
    benefits: ['Exfoliates nape and front neck area', 'Brilliant neck glow matches facial makeup perfectly'],
    ingredients: ['Rica chocolate face wax base'],
    skinType: 'Dry and dull neck skin',
    procedure: ['Antiseptic neck cleanse, spatula apply, quick strip release, oil massage'],
    aftercare: ['Avoid rich active necklaces that scratch skin'],
    safety: ['Verify thyroid zone pressure is minimal'],
    hygiene: ['Sanitized bed wrap and tools'],
    imageSeed: 'neck_wax'
  },
  {
    id: 'thread-14',
    name: 'Forehead Face Waxing',
    category: 'Threading & Face Wax',
    price: 129,
    durationMinutes: 10,
    benefits: ['Extremely tidy forehead with lasting skin smoothness'],
    ingredients: ['Peelable honey face wax'],
    skinType: 'All forehead skins',
    procedure: ['Pore wash, soft wax painting, gentle peel, witch hazel mist'],
    aftercare: ['Avoid face scrubbing for 2 days'],
    safety: ['Protect eyebrows with shielding strips during wax spread'],
    hygiene: ['Hygienic face bands utilized'],
    imageSeed: 'forehead_wax'
  },
  {
    id: 'thread-15',
    name: 'Full Face Waxing (Brows, Forehead, Cheek, Chin, Jaw, Lip)',
    category: 'Threading & Face Wax',
    price: 400,
    durationMinutes: 30,
    benefits: ['Total face transformation visual glow', 'Slows down facial hair growth for weeks', 'Perfect exfoliated glass base'],
    ingredients: ['Rica Brazilian face wax', 'Aloe calm extract oil', 'Lavender water'],
    skinType: 'Dull facial skins with fine hair layers',
    procedure: ['Full facial double wash, apply thin wax film across sections sequentially, peel gently, soothing cucumber face sheet mask compression'],
    aftercare: ['Absolutely no heavy makeup or hot sun walks for 48 hours', 'Comfortable moisturizer'],
    safety: ['Strict patch test on cheek bone prior to complete flow'],
    hygiene: ['Brand-new sterilized mask, medical-grade double gloves used by therapist'],
    imageSeed: 'full_face_wax'
  },

  // --- D-TAN & BLEACH ---
  {
    id: 'dtan-1',
    name: 'Front D-Tan (Chest & Stomach area)',
    category: 'D-Tan & Bleach',
    price: 949,
    durationMinutes: 25,
    benefits: ['Saves skin from deep sun-darkening on torso', 'Removes dead environmental dirt deposits'],
    ingredients: ['Licorice extract', 'Lactic acid milk enzymes', 'Arbutin booster', 'Eucalyptus cooling extract'],
    skinType: 'Suntanned torso skin',
    procedure: ['Cleanse torso with mild antiseptic wipe', 'Apply generous thick layer of professional D-tan pack', 'Relax under cooling fan for 15 minutes', 'Moist cleaning massage and wipe down'],
    aftercare: ['Avoid using heavy hot water on chest/stomach for 24h', 'Moisturize skin with aloe gel'],
    safety: ['Do not apply on dynamic stomach sunburn blisters', 'Allergy test first'],
    hygiene: ['All disposable towels and clean mixing bowls provided'],
    imageSeed: 'front_dtan'
  },
  {
    id: 'dtan-2',
    name: 'Full Body D-Tan',
    category: 'D-Tan & Bleach',
    price: 1599,
    durationMinutes: 60,
    benefits: ['Whole body de-tanning visual boost', 'Hydrates body skin uniformly and fades hyperpigmentation lines'],
    ingredients: ['Saffron extracts', 'Ascorbic acid', 'Licorice extract'],
    skinType: 'Tanned tired body skins',
    procedure: ['Cleanse body skin, apply thick D-tan paste to full body segments, let absorb for 20 mins, dynamic full body soothing massage clean'],
    aftercare: ['Keep body in comfortable clothing, avoid strong perfumes'],
    safety: ['Therapist dynamically monitors whole body sensitivity during pack absorption'],
    hygiene: ['Dedicated fresh disinfected body wrappers and disposable sheet layouts'],
    imageSeed: 'full_body_dtan'
  },
  {
    id: 'dtan-3',
    name: 'Full Arms D-Tan',
    category: 'D-Tan & Bleach',
    price: 449,
    durationMinutes: 25,
    benefits: ['Perfect remedy for driving hand tan lines', 'Leaves arms beautifully bright and soft'],
    ingredients: ['Lactic soap base', 'Mulberry and cucumber extract juice'],
    skinType: 'All tanned arm types',
    procedure: ['Cleanse arms, apply O3+ D-tan pack segment, wait 15 minutes, refreshing massage removal'],
    aftercare: ['Apply high-quality sunscreen before going out'],
    safety: ['Adjust application time if skin starts tingling intensely'],
    hygiene: ['Disinfected cosmetic spatulas used only'],
    imageSeed: 'full_arms_dtan'
  },
  {
    id: 'dtan-4',
    name: 'Face & Neck D-Tan Pack',
    category: 'D-Tan & Bleach',
    price: 459,
    durationMinutes: 25,
    benefits: ['Instantly lightens dark facial edges and neck lines', 'Brings refreshing aesthetic balance'],
    ingredients: ['Eucalyptus active oils', 'Active milk lactic enzymes'],
    skinType: 'Dull facials and deeply tanned collars',
    procedure: ['Double face wash, thick D-tan face and neck application, let react for 15 mins, cool-stone facial compression'],
    aftercare: ['No soaps or face scrubs for 24 hours, stay hydrated'],
    safety: ['Keep pack strictly away from eyes. If contact happens, rinse immediately with cold sterilized water'],
    hygiene: ['Clean head bands, brand-new specialized facial sponges used per client'],
    imageSeed: 'face_neck_dtan'
  },
  {
    id: 'dtan-5',
    name: 'Full Legs D-Tan Pack',
    category: 'D-Tan & Bleach',
    price: 649,
    durationMinutes: 35,
    benefits: ['Fades visual leg lines due to sun exposures', 'Incredibly soft and moisturized thighs and calves'],
    ingredients: ['Turmeric extract powder', 'Rosewater essence', 'Licorice root'],
    skinType: 'All leg types with sun darkening',
    procedure: ['Wash legs, paste application, let stand for 20 minutes, gentle micro-bead rinse removal'],
    aftercare: ['Apply moisturizing daily body lotion after wash'],
    safety: ['Monitor leg capillary warmth under pack'],
    hygiene: ['Disposable spa linen layout used only'],
    imageSeed: 'legs_dtan'
  },
  {
    id: 'dtan-6',
    name: 'Chest Only D-Tan Pack',
    category: 'D-Tan & Bleach',
    price: 519,
    durationMinutes: 25,
    benefits: ['Clear upper chest line tanning', 'Fills skin cells with cooling menthol energy'],
    ingredients: ['Mint oil leaf extracts', 'Milk enzymes'],
    skinType: 'All chest skins',
    procedure: ['Sanitize chest, apply D-tan base, wait 15 mins, wash clean with cooling towel'],
    aftercare: ['Avoid scratching chest area'],
    safety: ['Check chest area for active skin flare-ups'],
    hygiene: ['Standard disposable sheets used safely'],
    imageSeed: 'chest_dtan'
  },
  {
    id: 'dtan-7',
    name: 'Back Only D-Tan Pack',
    category: 'D-Tan & Bleach',
    price: 519,
    durationMinutes: 25,
    benefits: ['Even-toned gorgeous back, ready for aesthetic deep neck wears'],
    ingredients: ['Lactic skin whitener', 'Avocado butter factors'],
    skinType: 'Tanned dry back skin structures',
    procedure: ['Back wash, paste application, leave for 15 mins, rinse with therapeutic hot towel'],
    aftercare: ['Keep back skin hydrated with soft cooling cream'],
    safety: ['Check back skin carefully for cyst states'],
    hygiene: ['Brand new sanitized bowls and spatulas'],
    imageSeed: 'back_dtan'
  },
  {
    id: 'dtan-8',
    name: 'Face & Neck Luxury Bleach',
    category: 'D-Tan & Bleach',
    price: 399,
    durationMinutes: 25,
    benefits: ['Gently matches facial fine hair color to skin tone', 'Provides instant brightening effect'],
    ingredients: ['Hydrogen peroxide safe trace activator', 'Saffron cooling extract base cream'],
    skinType: 'All skins except highly sensitive, active acne prone skin',
    procedure: ['Verify bleach compound mix ratio, apply cooling pre-bleach skin serum, lay active bleach cream for 10-12 mins watchfully, wash with cold sponge, post-bleach cream seal'],
    aftercare: ['Do not step directly into the hot afternoon sun without sunglasses / umbrellas', 'No face wash for 24h'],
    safety: ['Strictly conduct a wrist patch test first. If intense itching occurs, discard immediately'],
    hygiene: ['Therapist strictly disinfected, sanitized mixing tray used once'],
    imageSeed: 'face_neck_bleach'
  },
  {
    id: 'dtan-9',
    name: 'Full Arms Bleach',
    category: 'D-Tan & Bleach',
    price: 539,
    durationMinutes: 25,
    benefits: ['Blends arm fleece hair into matching golden tones', 'Cleans deep skin cells'],
    ingredients: ['Cream beach factors', 'Ammonium compound', 'Beeswax base'],
    skinType: 'All skins with arm hair shadows',
    procedure: ['Cleanse arms, bleach paste coating, wait 15 minutes, remove with cool wash wash'],
    aftercare: ['Apply soothing aloe gel, avoid dynamic sun exposure'],
    safety: ['Do not scratch arms if tingling occurs'],
    hygiene: ['Disposable applicator blades usedly'],
    imageSeed: 'arms_bleach'
  },
  {
    id: 'dtan-10',
    name: 'Full Legs Bleach',
    category: 'D-Tan & Bleach',
    price: 649,
    durationMinutes: 35,
    benefits: ['Matches leg hair cleanly with golden sheen, glowing limbs'],
    ingredients: ['Golden activator minerals', 'Vitamin oil cream'],
    skinType: 'Tanned hairy leg skins',
    procedure: ['Wash and dry legs, even spatula bleach painting, leave 15 mins, cool rinse removal'],
    aftercare: ['Apply moisturizing lotion, wear loose trousers'],
    safety: ['Monitor thermal comfort across legs regions'],
    hygiene: ['Fresh disinfected sheet wrapper used'],
    imageSeed: 'legs_bleach'
  },
  {
    id: 'dtan-11',
    name: 'Chest Bleach',
    category: 'D-Tan & Bleach',
    price: 519,
    durationMinutes: 25,
    benefits: ['Matches chest hair to skin visual background'],
    ingredients: ['Mild activator chemical base', 'Aloe vera blend'],
    skinType: 'Normal skins',
    procedure: ['Cleanse torso, apply peach golden bleach, rinse after 12 mins with cool splash'],
    aftercare: ['Avoid tight inner vests'],
    safety: ['Verify user has no chest scar'],
    hygiene: ['Autoclaved bowls only'],
    imageSeed: 'chest_bleach'
  },
  {
    id: 'dtan-12',
    name: 'Front Bleach combo',
    category: 'D-Tan & Bleach',
    price: 539,
    durationMinutes: 25,
    benefits: ['Clear look on torso area'],
    ingredients: ['Hydrogen peroxide safe trace', 'Cream base'],
    skinType: 'All skins',
    procedure: ['Cleanse torso, lay bleach cream 12 mins, clean off with cold water'],
    aftercare: ['Keep cool and hydrated'],
    safety: ['Low concentration active activator counts'],
    hygiene: ['Sterilized tools and clean clothes'],
    imageSeed: 'front_bleach'
  },
  {
    id: 'dtan-13',
    name: 'Back Bleach Cream',
    category: 'D-Tan & Bleach',
    price: 539,
    durationMinutes: 25,
    benefits: ['Matches upper back hairs golden tint, clears active tan'],
    ingredients: ['Lavender soothing factors', 'Mild active bleachers'],
    skinType: 'Dry of tanned back skin structures',
    procedure: ['Apply bleach base safely, wait 12 mins, wash with back sponge'],
    aftercare: ['Avoid dynamic heavy workouts'],
    safety: ['Verify skin is not broken'],
    hygiene: ['Disposable gloves used continuously'],
    imageSeed: 'back_bleach'
  },
  {
    id: 'dtan-14',
    name: 'Stomach Bleach Cream',
    category: 'D-Tan & Bleach',
    price: 499,
    durationMinutes: 25,
    benefits: ['Matches belly hairs for perfect visual skin glow'],
    ingredients: ['Aloe vera base blend', 'Mild bleach compounds'],
    skinType: 'All skins',
    procedure: ['Belly cleanse, spatula lay, rinse with cooling towel after 12 mins'],
    aftercare: ['Moisturize tummy'],
    safety: ['Low active count on stomach skin'],
    hygiene: ['Clean sanitized equipment only'],
    imageSeed: 'stomach_bleach'
  },
  {
    id: 'dtan-15',
    name: 'Full Body Bleach Luxury Package',
    category: 'D-Tan & Bleach',
    price: 1559,
    durationMinutes: 60,
    benefits: ['Consistent glowing visual golden tone across full body', 'Exquisite pre-bridal choice'],
    ingredients: ['24K colloidal gold mineral activator', 'High performance soothing bleach cream'],
    skinType: 'Wedding and festive prepped normal body skins',
    procedure: ['Sequential body sanitization, systematic bleach cream layer, let activate 12-15 mins, cleansing body wash and botanical body butter spa massage'],
    aftercare: ['Strictly no direct heavy sun exposure or sauna visit for 48 hours'],
    safety: ['Therapist inspects full body active response every 3 minutes dynamically'],
    hygiene: ['Sanitary kit split-open per client, disinfected spa room bedding'],
    imageSeed: 'full_body_bleach'
  },
  {
    id: 'dtan-16',
    name: 'Half Legs Bleach Pack',
    category: 'D-Tan & Bleach',
    price: 399,
    durationMinutes: 25,
    benefits: ['Golden tone on calf area hair', 'Removes ankle tan lines'],
    ingredients: ['Cream starch bases', 'Vitamin oils'],
    skinType: 'Tanned calf skins',
    procedure: ['Wash calf, apply cream base, wait 12 mins, rinse off'],
    aftercare: ['Keep moisturized with soft gel'],
    safety: ['Check ankles for active scratches'],
    hygiene: ['Disposable towels standard with disinfected layouts'],
    imageSeed: 'half_legs_bleach'
  },

  // --- HAIR SERVICES ---
  {
    id: 'hair-1',
    name: 'Loreal Expert Anti-Dandruff Treatment',
    category: 'Hair Services',
    price: 1299,
    durationMinutes: 45,
    benefits: ['Zinc Pyrithione targets dandruff causing fungi', 'Clarity and deep moisturization to itchy scalp', 'Leaves hair voluminous and silky'],
    ingredients: ['Zinc Pyrithione active', 'Salicylic Acid scalper tool', 'Tea tree essential oil', 'Menthol coolants'],
    skinType: 'Flaky, itchy scalp of all hair textures',
    procedure: ['Anti-dandruff deep shampoo scalp wash', 'Concentrated salicylic scalp scrub massage (10 mins)', 'Anti-dandruff conditioning spa mask overlay', 'Scalp vapor steam (5 mins)', 'Washed clean and cold blow dry style'],
    aftercare: ['Wash hair other day with recommended sulfate-free tea-tree shampoo', 'Do not scratch scalp with sharp nails'],
    safety: ['Adjust vapor steam nozzle distance to avoid hot burns on ear tips'],
    hygiene: ['Autoclaved scalp scraping combs and pristine clean towels loaded per customer segment'],
    imageSeed: 'hair_dandruff'
  },
  {
    id: 'hair-2',
    name: 'Loreal Hydrating Spa (Hair Nourishment)',
    category: 'Hair Services',
    price: 1299,
    durationMinutes: 45,
    benefits: ['Deep nourishment lock into dry frizzy hair shafts', 'Restores natural shine and elastic bounce', 'Soothes hair static charge'],
    ingredients: ['Water lily flower extracts', 'Purified hydrating lipids', 'Argan oil core complex', 'Panthenol (Pro-Vitamin B5)'],
    skinType: 'Extremely dry, color-treated, chemically straightened or brittle hair',
    procedure: ['Hydration shampoo cleansing', 'Apply luxury hair spa cream with active scalp defense concentrate', 'Relaxing scalp and neck pressure massage (15 mins)', 'Micro-vapor ozone steam spray', 'Cold water wash lock and soft blow dry style'],
    aftercare: ['Keep hair safe from dusty open winds', 'Do not tie hair too tightly immediately'],
    safety: ['Check hair strength, adjust hydration level of spa cream accordingly'],
    hygiene: ['Sterilized mixing bowls, therapist disinfected prior to touch, sterile hair towels'],
    imageSeed: 'hair_hydrading_spa'
  },
  {
    id: 'hair-3',
    name: 'Dry Head Massage (Traditional stress relief)',
    category: 'Hair Services',
    price: 179,
    durationMinutes: 10,
    benefits: ['Instant relief from tension headache', 'Boots oxygen circulation to scalp hair follicles'],
    ingredients: ['Menthol cooling cooling mist', 'Camphor water extracts'],
    skinType: 'All stressed mind/head domains',
    procedure: ['Client sits comfortably, adjust neck towel, rhythmic dry fingers pressure scalp massage (10 mins)'],
    aftercare: ['Drink warm tea or water, close eyes for 5 mins'],
    safety: ['Avoid excessive pressure on temple bones or neck vertebrae joints'],
    hygiene: ['Therapist disinfected hands cleanly first'],
    imageSeed: 'dry_head_massage'
  },
  {
    id: 'hair-4',
    name: 'Pure Coconut Oil Scalp Massage',
    category: 'Hair Services',
    price: 419,
    durationMinutes: 20,
    benefits: ['Traditional Ayurvedic hot-oil treatment', 'Deeply conditions hair roots, prevents premature graying'],
    ingredients: ['100% Cold-Pressed Extra Virgin Coconut oil', 'Curry leaf extract', 'Bringharaj extracts'],
    skinType: 'Dry weak hair roots, hot body systems wishing coolness',
    procedure: ['Warm coconut oil to comfortable temperature, dissect hair lines, apply oil to scalp using sterile cotton swabs, traditional deep pressure points massage'],
    aftercare: ['Leave oil in scalp for at least 2 hours before washing with shampoo'],
    safety: ['Strict warm oil temperature verification to prevent scalp burns'],
    hygiene: ['Sterilized oil cups, fresh disinfected cotton swabs used per client'],
    imageSeed: 'coconut_oil_massage'
  },
  {
    id: 'hair-5',
    name: 'Pure Sweet Almond Oil Scalp Massage',
    category: 'Hair Services',
    price: 419,
    durationMinutes: 20,
    benefits: ['Rich Vitamin E locks moisture into thinning hair line', 'Superb calming massage restores hair thickness and shine'],
    ingredients: ['Premium Sweet Almond (Prunus dulcis) Oil', 'Vitamin E oil drops', 'Lavender drops'],
    skinType: 'Thinning dry hair, high stress levels',
    procedure: ['Apply lukewarm sweet almond oil to scalp, slow-paced deep circulation massage (15 mins), shoulder neck massage (5 mins)'],
    aftercare: ['Wash hair next morning with light baby shampoo'],
    safety: ['Check almond oil allergy prior to dynamic application'],
    hygiene: ['Clinical grade disinfected workspace setup'],
    imageSeed: 'almond_oil_massage'
  },
  {
    id: 'hair-6',
    name: 'Organic Henna Application (Hair colouring & conditioning)',
    category: 'Hair Services',
    price: 385,
    durationMinutes: 30,
    benefits: ['Natural reddish-brown hair coloring sheen', 'Closes hair cuticle scales, thickens hair layers naturally'],
    ingredients: ['100% Pure Rajasthani Henna (Mehendi) powder', 'Amla extract powder', 'Shikakai extract powder', 'Tea-decoction water'],
    skinType: 'Gray hair coverage, normal and oily hair types',
    procedure: ['Comb hair cleanly, section partition, apply wet herbal henna paste onto scalp and hair strands uniformly, roll hair into neat visual bun', 'Wrap with clean shower cap'],
    aftercare: ['Leave henna on hair for 2-3 hours strictly', 'Rinse with fresh room temperature plain water only (no shampoo for first 24h)'],
    safety: ['Keep henna paste away from eyes. Do patch test near neck line first'],
    hygiene: ['Disposable gloves, single use applicator brushes, customized client shoulder sheets'],
    imageSeed: 'henna_application'
  },
  {
    id: 'hair-7',
    name: 'Root Touch-Up (Professional hair coloring)',
    category: 'Hair Services',
    price: 385,
    durationMinutes: 30,
    benefits: ['Perfect professional grey coverage for roots', 'Matches organic visual hair color perfectly'],
    ingredients: ['Ammonia-free professional cream coloring base', 'Argan oils protective complex', 'Developer cream'],
    skinType: 'Gray hair strands, aging beautiful hair roots',
    procedure: ['Pin hairs back, mix cream formulation, apply exclusively to root growth (up to 2 inches of gray)', 'Leave to dry for 30 mins', 'Rinse with color damage prevention lock shampoo'],
    aftercare: ['Use color-protect shampoo on subsequent washes, avoid heavy swimming chlorine'],
    safety: ['Mandatory patch test on inner wrist 24 hours prior to first dye use'],
    hygiene: ['All sterilizable plastic bowls and hair dye combs sterilized perfectly'],
    imageSeed: 'hair_root_touchup'
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Nice Look Aloe Honey Post-Wax Soothing Gel',
    price: 299,
    volume: '200 ml',
    category: 'Waxing Care',
    keyIngredients: ['Pure Aloe Vera Juice', 'Organic Mountain Honey', 'Cucumber Extract', 'Pro-Vitamin B5'],
    benefit: 'Soothes redness, keeps pores cool, and provides instant skin hydration after any waxing session.',
    rating: 4.8
  },
  {
    id: 'prod-2',
    name: 'Nice Look K-Glass Radiance Cream',
    price: 399,
    volume: '50 g',
    category: 'Facial Care',
    keyIngredients: ['Niacinamide (5%)', 'Hyaluronic Acid', 'Centella Asiatica (Cica)', 'Snail Secretion Filtrate'],
    benefit: 'Gives the face a translucent, hydrated, glass-like shine while reinforcing the skin barrier.',
    rating: 4.9
  },
  {
    id: 'prod-3',
    name: 'Nice Look Tea Tree Anti-Bumps Spray',
    price: 249,
    volume: '100 ml',
    category: 'After-Wax Care',
    keyIngredients: ['Australian Tea Tree Oil', 'Witch Hazel', 'Salicylic Acid', 'Allantoin'],
    benefit: 'Prevents ingrown hairs and post-wax pimples on arms, legs, back or stomach.',
    rating: 4.7
  },
  {
    id: 'prod-4',
    name: 'Nice Look Gold Radiance Facial Serum',
    price: 499,
    volume: '30 ml',
    category: 'Facial Luxe',
    keyIngredients: ['Colloidal 24K Gold Particles', 'Saffron Extract', 'Rosehip Oil', 'Wheatgerm Oil'],
    benefit: 'Deeply restores dull skin layers, adding a premium visual golden shimmer and cell renewal.',
    rating: 4.9
  },
  {
    id: 'prod-5',
    name: 'Nice Look Rosemary Mint Foot Therapeutic Balm',
    price: 199,
    volume: '100 g',
    category: 'Pedicure Care',
    keyIngredients: ['Menthol', 'Rosemary Oil Extract', 'Camphor Oil', 'Shea Butter'],
    benefit: 'Softens hard, rough dead heels while relieving muscular pressure and aches.',
    rating: 4.6
  }
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev-1',
    customerName: 'Aishwarya Sen',
    serviceName: 'Korean Glass Skin Facial',
    rating: 5,
    text: 'Oh my goodness, this facial is magical! My skin literally looks like liquid glass. The technician was extremely neat and did dynamic massage pressure perfectly. Must try in Bangalore!',
    date: '2026-05-25',
    reply: 'Thank you Aishwarya! We are thrilled to see your gorgeous face glowing with our K-Glass aesthetic.'
  },
  {
    id: 'rev-2',
    customerName: 'Priya Narayanan',
    serviceName: 'Complete Rica Waxing',
    rating: 5,
    text: 'Highly professional waxing. Usually I get very red skin bumps, but Rica is colophony free, so my arms and legs have no redness at all. The disposable linen sheets are super clean.',
    date: '2026-05-24',
    reply: 'Thank you Priya! We practice medical-grade hygiene so your experience remains safe and comfortable.'
  },
  {
    id: 'rev-3',
    customerName: 'Meera Rao',
    serviceName: 'Eyebrows Cotton Threading',
    rating: 4,
    text: 'Very swift brows. The technician holds skin with maximum tight care and the soothing cooling rose aloe vera gel at the end was so cool.',
    date: '2026-05-22',
    reply: 'Thank you Meera! We keep eyebrows sharp and elegant.'
  }
];

export const BANGALORE_LANDMARKS = [
  { name: 'Koramangala 4th Block, Bengaluru', lat: 12.9343, lng: 77.6244 },
  { name: 'Indiranagar 100 Feet Rd, Bengaluru', lat: 12.9719, lng: 77.6412 },
  { name: 'Jayanagar 4th Block, Bengaluru', lat: 12.9279, lng: 77.5909 },
  { name: 'Whitefield Main Rd, Bengaluru', lat: 12.9698, lng: 77.7500 },
  { name: 'Malleswaram 15th Cross, Bengaluru', lat: 13.0031, lng: 77.5684 },
  { name: 'HSR Layout Sector 2, Bengaluru', lat: 12.9119, lng: 77.6384 },
  { name: 'MG Road, Shivaji Nagar, Bengaluru', lat: 12.9756, lng: 77.6067 },
  { name: 'Yelahanka New Town, Bengaluru', lat: 13.0981, lng: 77.5956 }
];
